#! /bin/csh -f
#

set args=($*)

set mdir = ~/teunix/Backup

set all=(`echo mlocate.*.db`)

foreach a ($all)
   echo "# $a `stat -c %y $a`"
   mlocate -d $a $args
end

set all=(`echo plocate.*.db`)

foreach a ($all)
   echo "# $a `stat -c %y $a`"
   plocate -d $a $args
end

