#! /usr/bin/env python
#
# print some abstract of the global key shortcuts in KDE
#
# another option is to use KDE native tools, e.g.
#   kreadconfig5 --file ~/.config/kglobalshortcutsrc --group kded5  --key 'Show System Activity'
#


import os, sys

friendly = '_k_friendly_name'
title = ''
fname = os.environ['HOME'] + '/.config/kglobalshortcutsrc'

lines = open(fname).readlines()
for line in lines:
    line = line.strip()
    word = line.split('=')
    if len(line) == 0:
        continue
    #print("LINE: %s (%d)" % (line,len(line)))
    if line[0] == '[':
        group = line[1:-1]    # @todo fix the brittle -2
        print("%-70s %s" % ('#',group))
        continue
    if word[0] == friendly:
        title = word[1]
        print("%-70s     %s" % ('#',title))        
        continue
    if len(word) < 2:
        # print("Warning %s (%d)" % (word[0], len(word)))
        continue;
    key = word[1].split(',')
    if key[0] == 'none':
        continue
    if len(key) != 3:
        # @todo    deal with \, to ensure it's embedded ,
        #print("Warning key: %s" % word[1])
        continue
    if len(key[0]) > 0:
        print("%-50s : %s" % (key[2],key[0]))
    else:
        print("%-50s : [%s]" % (key[2],key[1]))
        




